baseURL = "https://jaimeesqueda.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "Bitácora de Viaje Jaime Esqueda Velasco"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = "01100"
  # Hey Explorer aquí pon tu twitter 👇
  twitter_handle = "@JaimeEsqueda"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
